export const customResponses = {
    AddrNotRecievedErr: "Address not received",
    IncorrectPassword: "Incorrect password",
    EmailNotExists: "email does not exist",
    EmailAlreadyExists: "email already exists",
    EmailAlreadyVerified: "This email is already verified",
    EmailOrPhoneNotProvider: "Email or Phone number must be provided",
    EmailVerifiedSuccess: "Email Successfully Verified",
    InvalidOtp: "Please provide the correct OTP",
    OtpSentErr: "could not send otp! Please try again after some time",
    OtpSentSuccess: "Successfully sent OTP",
    OtpNotExistErr: "Otp not generated",
    OtpNotReceivedErr: "Otp not received",
    PhoneVerifiedSuccess: "Phone number successfully Verified",
    ExpiredOtp: "OTP is expired",
    PhoneAlreadyExists: "Phone already exists",
    PasswordResetSuccess: "Password Changed Successfully",
    SignOutSuccess: "User Signedout Successfully",
    UserDeleteSuccess: "User Deleted Successfully",
    UserAlreadyExists: "User already exists",
    MessageNotReceived: 'message content not received',
    NoChatExists: "No chat exists for the user",
    UserNotFound: "Invalid Id ",
    LessGroupMember: "There should be atleast three members in a group",
    InvalidGroup: "No group with id exists",
    GroupUpdateSuccess: "Group Updated Successfully",
    GroupPermissionErr: "You don't have permission for this operation",
    GroupMemberNotFound: "No member with this id exists in the group",
    ChatDeletedSuccess: "Chat is deleted successfully",
    MessageNotFound: "No message found",
    MessageDeletedSuccess: "Successfully Deleted Message",
    PhoneNotAvailable: "No phone number attached to your account",
    EmailNotAvailable: "Email not attached to this account",
    InvalidAuthType: "You've signed through",
    updateStatusSuccess: "Successfully updated user's status"
}